name: Deploy Averite website on server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Create .env file
    #     run: |
    #       echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env
    #       echo "NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}" >> .env

      - name: Build and push Docker images
        run: |
          docker build -t vladigpasev/averite:${{ github.sha }} .
          docker push vladigpasev/averite:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "Connecting to server"
            cd ~/averite
            echo "Pulling new Docker images"
            docker pull vladigpasev/averite:${{ github.sha }}
            echo "Stopping and removing old containers"
            docker stop averite || true
            docker rm averite || true
            echo "Running the new Docker container"
            docker run -d --name averite -p 3000:3000 vladigpasev/averite:${{ github.sha }}
            echo "Deployment complete"